kind: Template
apiVersion: v1
metadata:
  name: neo4j-ephemeral
  annotations:
    openshift.io/display-name: 'Neo4j (Ephemeral)'
    description: "Neo4j Graph Database. This template will create service without persistent storage."
    tags: "graph,database,neo4j"
    iconClass: "icon-datavirt"

parameters:
  - name: NEO4J_NAME
    displayName: "Neo4j Name"
    description: "A reference to Neo4j name."
    from: "[a-zA-Z0-9]{10}"
    value: "neo4j"
    required: true

  - name: NEO4J_PASSWORD
    displayName: "Neo4j Password"
    description: "A reference to Neo4j password."
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true

  - name: NEO4J_DOMAIN_URL
    displayName: "Neo4j Domain URL"
    description: "A reference to Neo4j domain URL."
    from: "[a-zA-Z0-9]{100}"

  - name: NEO4J_JAVA_MEMORY
    displayName: "Neo4j Java Memory"
    description: "Maximum amount of memory the Neo4j can use."
    value: "1G"
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: '${NEO4J_NAME}'
    stringData:
      NEO4J_PASSWORD: '${NEO4J_PASSWORD}'

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${NEO4J_NAME}-web"
    spec:
      ports:
        - name: "neo4j-http"
          port: "7474"
        - name: "neo4j-https"
          port: "7473"
      selector:
        name: "${NEO4J_NAME}"

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${NEO4J_NAME}-bolt"
    spec:
      ports:
        - name: "neo4j-bolt"
          port: "7687"
      selector:
        name: "${NEO4J_NAME}"

  - kind: Route
    apiVersion: v1
    metadata:
      name: "${NEO4J_NAME}"
    spec:
      host: ${NEO4J_DOMAIN_URL}
      to:
        kind: Service
        name: ${NEO4J_NAME}-web
      port:
        targetPort: neo4j-http

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${NEO4J_NAME}"
      label:
        name: "${NEO4J_NAME}"
    spec:
      replicas: 1
      selector:
        name: "${NEO4J_NAME}"
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: "${NEO4J_NAME}"
        spec:
          containers:
            - env:
              - name: NEO4J_JAVA_OPTS
                value: '-Xms${NEO4J_JAVA_MEMORY} -Xmx${NEO4J_JAVA_MEMORY}'
              - name: NEO4J_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: '${NEO4J_NAME}'
                    key: NEO4J_PASSWORD
              name: 'neo4j'
              image: 'dimaskiddo/alpine:neo4j-3.5'
              imagePullPolicy: Always
              ports:
                - containerPort: 7474
                  protocol: TCP
                - containerPort: 7473
                  protocol: TCP
                - containerPort: 7687
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 7687
                timeoutSeconds: 1
              volumeMounts:
                - name: neo4j-data
                  mountPath: "/var/lib/neo4j/data"
          volumes:
            - name: neo4j-data
              emptyDir: {}
      triggers:
        - type: ConfigChange
