kind: Template
apiVersion: v1
metadata:
  name: apache-kafka-persistent
  annotations:
    openshift.io/display-name: 'Apache Kafka'
    description: "Apache Kafka. You must have persistent volumes available in your cluster to use this template."
    tags: "messaging,queue,apache,kafka"
    iconClass: "icon-scala"

parameters:
  - name: KAFKA_NAME
    displayName: "Kafka Name"
    description: "A reference to Kafka name."
    from: "[a-zA-Z0-9]{10}"
    value: "kafka"
    required: true

  - name: KAFKA_VOLUME_CAPACITY
    displayName: "Kafka Volume Capacity"
    description: "Volume space available for kafka data, e.g. 512Mi, 2Gi."
    value: "1Gi"
    required: true

objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${KAFKA_NAME}"
    spec:
      ports:
        - name: "zookeeper"
          port: "2181"
        - name: "kafka"
          port: "9092"
      selector:
        name: "${KAFKA_NAME}"

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${KAFKA_NAME}"
      label:
        name: "${KAFKA_NAME}"
    spec:
      replicas: 1
      selector:
        name: "${KAFKA_NAME}"
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: "${KAFKA_NAME}"
        spec:
          containers:
            - name: 'kafka'
              image: 'dimaskiddo/alpine:kafka-2.7'
              imagePullPolicy: Always
              ports:
                - containerPort: 2181
                  protocol: TCP
                - containerPort: 9092
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 9092
                timeoutSeconds: 1
              volumeMounts:
                - name: kafka-data
                  mountPath: "/data"
          volumes:
            - name: kafka-data
              persistentVolumeClaim:
                claimName: ${KAFKA_NAME}
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${KAFKA_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: '${KAFKA_VOLUME_CAPACITY}'
